[project]
name = "msc-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "betacal>=1.1.0",
    "calibra>=0.3.2",
    "great-tables>=0.23.0",
    "hockey-rink>=1.1.4",
    "ijson>=3.5.1",
    "imbalanced-learn>=0.14.2",
    "lightgbm>=4.6.0",
    "marimo==0.24.0",
    "matplotlib>=3.10.9",
    "numba>=0.66.0",
    "numpy>=2.4.6",
    "optuna>=4.9.0",
    "optuna-integration[lightgbm]>=4.9.0",
    "orjson>=3.11.9",
    "plotnine[extra]>=0.15.7",
    "polars>=1.41.2",
    "pyarrow>=24.0.0",
    "scikit-learn>=1.9.0",
    "shap>=0.49.1",
    "xgboost>=3.3.0",
]

[tool.marimo.runtime]
pythonpath = ["scripts"]

[dependency-groups]
dev = [
    "pydantic-ai>=2.8.0",
    "pytest>=9.1.1",
]

[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
section-order = [
    "standard-library", # Built-in Python modules (sys, os, etc.)
    "third-party",      # Additional libraries (numpy, pandas, etc.)
    "first-party",      # custom scripts and internal packages
    "local-folder"      # Relative imports (e.g., from . import utils)
]
known-first-party = ["scripts"]
